# Generated by Django 5.1 on 2024-08-25 03:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=40, unique=True)),
                ("address", models.TextField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Banks",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=40, unique=True)),
                (
                    "readable_id",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("address", models.TextField(max_length=100)),
                ("regitration_date", models.DateField()),
                ("employee_count", models.SmallIntegerField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contact", models.CharField(max_length=30)),
                ("website", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("amount", models.FloatField()),
                ("date", models.DateField()),
                (
                    "status",
                    models.SmallIntegerField(
                        verbose_name=[("Paid", 1), ("Due", 2), ("Initiated", 3)]
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="credits.company",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="credits.bank",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Loans",
            },
        ),
        migrations.CreateModel(
            name="Turnover",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("total", models.FloatField(default=0.0)),
                ("profit", models.FloatField(default=0.0)),
                ("fiscal_year", models.SmallIntegerField()),
                ("report_date", models.DateField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="credits.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Turnovers",
            },
        ),
    ]
