# Generated by Django 5.1 on 2024-08-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="contact",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.CharField(max_length=50),
        ),
    ]
